name: Build Container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  container:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          push: true
