name: Deploy Website

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  calendar_sync:
    runs-on: ubuntu-latest
    name: Sync Calendar
    steps:
      - uses: acm-uic/calsync@main
        with:
          discord-guild-id: ${{ secrets.DISCORD_EVENTS_SYNC_DISCORD_GUILD_ID }}
          discord-bot-token: ${{ secrets.DISCORD_EVENTS_SYNC_DISCORD_BOT_TOKEN }}
          discord-application-id: ${{ secrets.DISCORD_EVENTS_SYNC_DISCORD_APPLICATION_ID }}
          google-calendar-id: ${{ secrets.DISCORD_EVENTS_SYNC_GOOGLE_CALENDAR_CALENDAR_ID }}
          google-api-key: ${{ secrets.DISCORD_EVENTS_SYNC_GOOGLE_CALENDAR_API_KEY }}
  publish:
    runs-on: ubuntu-latest
    name: Publish to GitHub Pages
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Install pandoc and make
        run: sudo apt install pandoc make --yes
        
      - name: Install XSLTProc
        run: sudo apt install xsltproc
        
      - name: One Make to Rule them all
        run: make all

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
